# ===================================================================
# PERFIL DE PRODUCCIÓN (prod)
# Optimizado para seguridad, rendimiento y fiabilidad.
# ===================================================================
spring:
  # Conexión a la base de datos de producción usando variables de entorno
  datasource:
    url: ${DATABASE_URL} # Ej: jdbc:mysql://prod-db.host:3306/academia_prod
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Nunca usar 'create' o 'update' en producción
      dialect: org.hibernate.dialect.MySQLDialect

  # Configuración de Redis para caché en producción
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

  # Credenciales de correo desde variables de entorno
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

# Logging para producción: Menos verboso, enfocado en errores
logging:
  level:
    root: INFO
    com.academia: WARN # Solo loguear advertencias y errores de nuestra aplicación

# JWT Secret y expiración desde variables de entorno
jwt:
  secret: ${JWT_SECRET} # ¡NUNCA hardcodear esto!
  expiration: 3600000 # 1 hora
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 minutos
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 días

app:
  auth:
    max-login-attempts: ${AUTH_MAX_LOGIN_ATTEMPTS:3}
    login-attempt-window-minutes: ${AUTH_LOGIN_ATTEMPT_WINDOW:1}
  security:
    allowed-origins: ${ALLOWED_ORIGINS} # Variable de entorno obligatoria
    max-session-duration-minutes: ${MAX_SESSION_DURATION:240} # 4 horas



