# ===================================================================
# CONFIGURACIÓN BASE - PROPIEDADES COMUNES A TODOS LOS ENTORNOS
# ===================================================================
spring:
  application:
    name: sistema-academico-enterprise

  # Perfil activo por defecto es 'dev'
  profiles:
    active: dev

  # Configuración JPA común
  jpa:
    open-in-view: false # Buena práctica para evitar problemas de rendimiento
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Configuración de Migraciones de Base de Datos
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history

  # Configuración de Serialización JSON
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: America/Bogota # Ajustado a tu zona horaria

  # Configuración de Correo (plantilla)
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Configuración de Documentación API
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Configuración de Actuator para Monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}

jwt:
  # Secret debe ser sobrescrito por variables de entorno en cada ambiente
  secret: ${JWT_SECRET:default-secret-key-for-development-only-must-be-changed-in-production}

  # Expiración del access token en milisegundos (15 minutos por defecto)
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}

  # Expiración del refresh token en milisegundos (7 días por defecto)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

# ===================================================================
# CONFIGURACIÓN DE APLICACIÓN ESPECÍFICA
# ===================================================================
app:
  # Configuración de rate limiting para autenticación
  auth:
    max-login-attempts: ${AUTH_MAX_LOGIN_ATTEMPTS:5}
    login-attempt-window-minutes: ${AUTH_LOGIN_ATTEMPT_WINDOW:1}

  # Configuración de seguridad
  security:
    # Dominios permitidos para CORS (separados por coma)
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

    # Duración máxima de sesión en minutos
    max-session-duration-minutes: ${MAX_SESSION_DURATION:480}
