# ===================================================================
# PERFIL DE DESARROLLO (dev)
# Optimizado para la productividad del desarrollador local.
# ===================================================================
spring:
  # Conexión a la base de datos local de desarrollo
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true # Muestra las queries SQL en la consola
    hibernate:
      ddl-auto: validate # Valida que el esquema de la BD coincida con las entidades
      dialect: org.hibernate.dialect.MySQLDialect

  # Desactivar caché en desarrollo para ver los cambios inmediatamente
  cache:
    type: none

  # Habilitar H2 Console para inspeccionar la BD (si se usa H2 temporalmente)
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuración de Logging Detallado
logging:
  level:
    root: INFO
    com.academia: DEBUG # Log detallado para nuestro código
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG # Muestra las queries SQL generadas
    org.hibernate.type.descriptor.sql: TRACE # Muestra los parámetros de las queries

# Configuración JWT para desarrollo
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-token-expiration: 604800000

app:
  auth:
    max-login-attempts: 10 # Más permisivo en desarrollo
    login-attempt-window-minutes: 5
  security:
    allowed-origins: "http://localhost:3000,http://localhost:8080,http://localhost:4200"

